### PR TITLE
Update lastpage color

### PR DESCRIPTION
**Pull request by rishivyas1969**

### CODE REVIEW

**Comment by RitikaShrestha-me** [comment]
can i work on this?

**Comment by rishivyas1969** [comment]
For hacktoberfest..!?

**Comment by RitikaShrestha-me** [comment]
Yes

**Comment by RitikaShrestha-me** [comment]
Yes

**Comment by rishivyas1969** [comment]
Yeah...sure..but its not my repo. Its my friend's..we also want you get
t-shirt too. So, do any small change i will tell my friend to merge it..

**Pull request merged**
